
import { GoogleGenAI } from "@google/genai";

const MODEL_NAME = 'gemini-2.5-flash-image';

export const transformImage = async (
  sourceBase64: string,
  referenceBase64: string,
  additionalInstructions: string = ""
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Strip metadata from base64 if present
  const sourceData = sourceBase64.split(',')[1] || sourceBase64;
  const referenceData = referenceBase64.split(',')[1] || referenceBase64;

  const prompt = `
    TASK: Pure Style Transfer (Extract Style, Preserve Source Content).
    
    INSTRUCTIONS:
    1. STYLE EXTRACTION: Analyze the first image (STYLE REFERENCE). Extract ONLY its aesthetic DNA: color grading, lighting profile, artistic medium (e.g., oil painting, cinematic photo, 3D render), texture, grain, and mood. 
    2. CONTENT ISOLATION: COMPLETELY IGNORE the subject matter, people, objects, and spatial composition of the STYLE REFERENCE image. Do not include any elements from it in the final result.
    3. SOURCE PRESERVATION: Analyze the second image (SOURCE). This is the ONLY source of content. 
    4. RECONSTRUCTION: Redraw the SOURCE image using the stylistic DNA extracted in Step 1. 
    5. IDENTITY LOCK: The person's identity, facial structure, expression, and exact pose from the SOURCE image MUST remain 100% unchanged.
    
    ${additionalInstructions ? `ADDITIONAL USER PREFERENCES: ${additionalInstructions}` : ""}
    
    Output the final stylized image.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: referenceData,
            },
          },
          {
            inlineData: {
              mimeType: 'image/png',
              data: sourceData,
            },
          },
          {
            text: prompt
          }
        ]
      },
    });

    let imageUrl = '';
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error) {
    console.error("Gemini Transformation Error:", error);
    throw error;
  }
};
